name: tunecache
description: 音栈 TuneCache - 可缓存音乐到自有服务器的跨平台客户端
publish_to: none
version: 1.1.0+3

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  media_kit: ^1.2.6
  media_kit_libs_audio: ^1.0.7
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.3
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.3
  intl: ^0.19.0
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: []
